-- MySQL Script generated by MySQL Workbench
-- 08/11/15 17:13:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nogoblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nogoblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `nogoblog` ;

-- -----------------------------------------------------
-- Table `nogoblog`.`semesters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`semesters` (
  `semesters_id` INT NOT NULL,
  `semester_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`semesters_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`class` (
  `class_id` INT NOT NULL,
  `class_level` VARCHAR(45) NULL,
  `semester_fk` INT NOT NULL,
  PRIMARY KEY (`class_id`, `semester_fk`),
  INDEX `fk_class_semesters1_idx` (`semester_fk` ASC),
  CONSTRAINT `fk_class_semesters1`
    FOREIGN KEY (`semester_fk`)
    REFERENCES `nogoblog`.`semesters` (`semesters_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`subject` (
  `subject_id` INT NOT NULL,
  `subject_names` VARCHAR(30) NOT NULL,
  `class_fk` INT NOT NULL,
  `semester_fk` INT NOT NULL,
  PRIMARY KEY (`subject_id`, `class_fk`, `semester_fk`),
  INDEX `fk_subject_class1_idx` (`class_fk` ASC, `semester_fk` ASC),
  CONSTRAINT `fk_subject_class1`
    FOREIGN KEY (`class_fk` , `semester_fk`)
    REFERENCES `nogoblog`.`class` (`class_id` , `semester_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`score` (
  `score_id` INT NOT NULL AUTO_INCREMENT,
  `score_total` INT NULL,
  `subject_subject_id` INT NOT NULL,
  `subject_class_fk` INT NOT NULL,
  `subject_semester_fk` INT NOT NULL,
  PRIMARY KEY (`score_id`, `subject_subject_id`, `subject_class_fk`, `subject_semester_fk`),
  INDEX `fk_score_subject1_idx` (`subject_subject_id` ASC, `subject_class_fk` ASC, `subject_semester_fk` ASC),
  CONSTRAINT `fk_score_subject1`
    FOREIGN KEY (`subject_subject_id` , `subject_class_fk` , `subject_semester_fk`)
    REFERENCES `nogoblog`.`subject` (`subject_id` , `class_fk` , `semester_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`users` (
  `users_id` INT NOT NULL,
  `users_regtime` DATETIME NOT NULL,
  `users_name` VARCHAR(50) NOT NULL,
  `users_email` VARCHAR(50) NOT NULL,
  `users_pass` VARCHAR(8) NOT NULL,
  `class_fk` INT NOT NULL,
  `user_premium` ENUM('0','1') NULL,
  `user_score_fk` INT NOT NULL,
  `user_subject_fk` INT NOT NULL,
  `user_class_fk` INT NOT NULL,
  `user_semester_fk` INT NOT NULL,
  PRIMARY KEY (`users_id`, `class_fk`, `user_score_fk`, `user_subject_fk`, `user_class_fk`, `user_semester_fk`),
  INDEX `fk_users_class1_idx` (`class_fk` ASC),
  INDEX `fk_users_score1_idx` (`user_score_fk` ASC, `user_subject_fk` ASC, `user_class_fk` ASC, `user_semester_fk` ASC),
  CONSTRAINT `fk_users_class1`
    FOREIGN KEY (`class_fk`)
    REFERENCES `nogoblog`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_score1`
    FOREIGN KEY (`user_score_fk` , `user_subject_fk` , `user_class_fk` , `user_semester_fk`)
    REFERENCES `nogoblog`.`score` (`score_id` , `subject_subject_id` , `subject_class_fk` , `subject_semester_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question_content` VARCHAR(500) NOT NULL,
  `question_active` ENUM('0','1') NOT NULL,
  `subject_fk` INT NOT NULL,
  PRIMARY KEY (`question_id`, `subject_fk`),
  INDEX `fk_question_subject1_idx` (`subject_fk` ASC),
  CONSTRAINT `fk_question_subject1`
    FOREIGN KEY (`subject_fk`)
    REFERENCES `nogoblog`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`quest_choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`quest_choice` (
  `quest_choice_id` INT NOT NULL,
  `quest_choice_content` VARCHAR(45) NULL,
  `quest_choice_right` ENUM('0','1') NULL,
  `question_fk` INT NOT NULL,
  PRIMARY KEY (`quest_choice_id`, `question_fk`),
  INDEX `fk_quest_choice_question_idx` (`question_fk` ASC),
  CONSTRAINT `fk_quest_choice_question`
    FOREIGN KEY (`question_fk`)
    REFERENCES `nogoblog`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`user_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`user_answer` (
  `user_answer_id` INT NOT NULL,
  `user_answers` VARCHAR(45) NULL,
  `users_fk` INT NOT NULL,
  `quest_choice_fk` INT NOT NULL,
  `question_fk` INT NOT NULL,
  PRIMARY KEY (`user_answer_id`, `users_fk`, `quest_choice_fk`, `question_fk`),
  INDEX `fk_user_answer_users1_idx` (`users_fk` ASC),
  INDEX `fk_user_answer_quest_choice1_idx` (`quest_choice_fk` ASC, `question_fk` ASC),
  CONSTRAINT `fk_user_answer_users1`
    FOREIGN KEY (`users_fk`)
    REFERENCES `nogoblog`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_answer_quest_choice1`
    FOREIGN KEY (`quest_choice_fk` , `question_fk`)
    REFERENCES `nogoblog`.`quest_choice` (`quest_choice_id` , `question_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nogoblog`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nogoblog`.`admin` (
  `admin_id` INT NOT NULL,
  `admin_user_fk` INT NOT NULL,
  `score_score_id` INT NOT NULL,
  `score_subject_subject_id` INT NOT NULL,
  `score_subject_class_fk` INT NOT NULL,
  `score_subject_semester_fk` INT NOT NULL,
  PRIMARY KEY (`admin_id`, `admin_user_fk`, `score_score_id`, `score_subject_subject_id`, `score_subject_class_fk`, `score_subject_semester_fk`),
  INDEX `fk_admin_users1_idx` (`admin_user_fk` ASC),
  INDEX `fk_admin_score1_idx` (`score_score_id` ASC, `score_subject_subject_id` ASC, `score_subject_class_fk` ASC, `score_subject_semester_fk` ASC),
  CONSTRAINT `fk_admin_users1`
    FOREIGN KEY (`admin_user_fk`)
    REFERENCES `nogoblog`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_score1`
    FOREIGN KEY (`score_score_id` , `score_subject_subject_id` , `score_subject_class_fk` , `score_subject_semester_fk`)
    REFERENCES `nogoblog`.`score` (`score_id` , `subject_subject_id` , `subject_class_fk` , `subject_semester_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
