-- MySQL Script generated by MySQL Workbench
-- 08/10/15 10:32:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`semesters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`semesters` (
  `semesters_id` INT NOT NULL,
  `semester_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`semesters_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `class_id` INT NOT NULL,
  `class_level` VARCHAR(45) NULL,
  `semester_fk` INT NOT NULL,
  PRIMARY KEY (`class_id`, `semester_fk`),
  INDEX `fk_class_semesters1_idx` (`semester_fk` ASC),
  CONSTRAINT `fk_class_semesters1`
    FOREIGN KEY (`semester_fk`)
    REFERENCES `mydb`.`semesters` (`semesters_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `users_id` INT NOT NULL,
  `users_regtime` DATETIME NOT NULL,
  `users_name` VARCHAR(50) NOT NULL,
  `users_email` VARCHAR(50) NOT NULL,
  `users_pass` VARCHAR(8) NOT NULL,
  `class_fk` INT NOT NULL,
  `user_premium` ENUM('0','1') NULL,
  PRIMARY KEY (`users_id`, `class_fk`),
  INDEX `fk_users_class1_idx` (`class_fk` ASC),
  CONSTRAINT `fk_users_class1`
    FOREIGN KEY (`class_fk`)
    REFERENCES `mydb`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subject` (
  `subject_id` INT NOT NULL,
  `subject_names` VARCHAR(30) NOT NULL,
  `class_fk` INT NOT NULL,
  `semester_fk` INT NOT NULL,
  PRIMARY KEY (`subject_id`, `class_fk`, `semester_fk`),
  INDEX `fk_subject_class1_idx` (`class_fk` ASC, `semester_fk` ASC),
  CONSTRAINT `fk_subject_class1`
    FOREIGN KEY (`class_fk` , `semester_fk`)
    REFERENCES `mydb`.`class` (`class_id` , `semester_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question_content` VARCHAR(500) NOT NULL,
  `question_active` ENUM('0','1') NOT NULL,
  `subject_fk` INT NOT NULL,
  PRIMARY KEY (`question_id`, `subject_fk`),
  INDEX `fk_question_subject1_idx` (`subject_fk` ASC),
  CONSTRAINT `fk_question_subject1`
    FOREIGN KEY (`subject_fk`)
    REFERENCES `mydb`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`quest_choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quest_choice` (
  `quest_choice_id` INT NOT NULL,
  `quest_choice_content` VARCHAR(45) NULL,
  `quest_choice_right` ENUM('0','1') NULL,
  `question_question_id` INT NOT NULL,
  PRIMARY KEY (`quest_choice_id`, `question_question_id`),
  INDEX `fk_quest_choice_question_idx` (`question_question_id` ASC),
  CONSTRAINT `fk_quest_choice_question`
    FOREIGN KEY (`question_question_id`)
    REFERENCES `mydb`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`user_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_answer` (
  `user_answer_id` INT NOT NULL,
  `user_answers` VARCHAR(45) NULL,
  `quest_choice_fk` INT NOT NULL,
  `question_fk` INT NOT NULL,
  `users_fk` INT NOT NULL,
  PRIMARY KEY (`user_answer_id`, `quest_choice_fk`, `question_fk`, `users_fk`),
  INDEX `fk_user_answer_quest_choice1_idx` (`quest_choice_fk` ASC, `question_fk` ASC),
  INDEX `fk_user_answer_users1_idx` (`users_fk` ASC),
  CONSTRAINT `fk_user_answer_quest_choice1`
    FOREIGN KEY (`quest_choice_fk` , `question_fk`)
    REFERENCES `mydb`.`quest_choice` (`quest_choice_id` , `question_question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_answer_users1`
    FOREIGN KEY (`users_fk`)
    REFERENCES `mydb`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
